@echo
XCOPY /Y /H /R node_modules\bootstrap\dist\js\bootstrap.bundle.js src\assets\modules\bootstrap\
XCOPY /Y /H /R node_modules\bootstrap\dist\js\bootstrap.bundle.js.map src\assets\modules\bootstrap\
XCOPY /Y /H /R node_modules\datatables.net\js\jquery.dataTables.js src\assets\modules\datatables\
XCOPY /Y /H /R node_modules\fullcalendar\main.js src\assets\modules\fullcalendar\
XCOPY /Y /H /R node_modules\fullcalendar\locales\ru.js src\assets\modules\fullcalendar\locales\
XCOPY /Y /H /R node_modules\jquery\dist\jquery.min.js src\assets\modules\jquery\
XCOPY /Y /H /R node_modules\jquery\dist\jquery.min.map src\assets\modules\jquery\
XCOPY /Y /H /R node_modules\rrule\dist\es5\rrule-tz.js src\assets\modules\rrule\
XCOPY /Y /H /R node_modules\rrule\dist\es5\rrule-tz.js.map src\assets\modules\rrule\
XCOPY /Y /H /R node_modules\@mdi\font\fonts\materialdesignicons-webfont.woff2 src\assets\fonts\
XCOPY /Y /H /R node_modules\moment\moment.js src\assets\modules\moment\
XCOPY /Y /H /R node_modules\moment\locale\ru.js src\assets\modules\moment\
XCOPY /Y /H /R node_modules\flatpickr\dist\flatpickr.js src\assets\modules\flatpickr\
XCOPY /Y /H /R node_modules\flatpickr\dist\l10n\ru.js src\assets\modules\flatpickr\
XCOPY /Y /H /R node_modules\select2\dist\js\select2.full.js src\assets\modules\select2\
XCOPY /Y /H /R node_modules\select2\dist\js\i18n\ru.js src\assets\modules\select2\
XCOPY /Y /H /R node_modules\jquery-validation\dist\jquery.validate.js src\assets\modules\jquery-validation\
XCOPY /Y /H /R node_modules\jquery-validation\dist\localization\messages_ru.js src\assets\modules\jquery-validation\
XCOPY /Y /H /R node_modules\moment-timezone\builds\moment-timezone-with-data.js src\assets\modules\moment-timezone\
XCOPY /Y /H /R node_modules\@fullcalendar\moment-timezone\main.global.js src\assets\modules\moment-timezone\
XCOPY /Y /H /R node_modules\dragula\dist\dragula.js src\assets\modules\dragula\
