export const weatherStates = {
  200: { desc: 'гроза с небольшим дождем', icon: '/icons/weather/thunderstorms-rain.svg' },
  201: { desc: 'гроза с дождем', icon: '/icons/weather/thunderstorms-rain.svg' },
  202: { desc: 'гроза с сильным дождем', icon: '/icons/weather/thunderstorms-extreme-rain.svg'},
  210: { desc: 'небольшая гроза', icon: '/icons/weather/thunderstorms.svg' },
  212: { desc: 'сильная гроза', icon: '/icons/weather/thunderstorms.svg' },
  221: { desc: 'очень сильная гроза', icon: '/icons/weather/thunderstorms-extreme.svg' },
  230: { desc: 'гроза с мелким дождем', icon: '/icons/weather/thunderstorms-rain.svg' },
  231: { desc: 'гроза с средним дождем', icon: '/icons/weather/thunderstorms-rain.svg' },
  232: { desc: 'гроза с сильным дождем', icon: '/icons/weather/thunderstorms-extreme-rain.svg' },
  300: { desc: 'слабая морось', icon:  '/icons/weather/drizzle.svg' },
  301: { desc: 'морось', icon:  '/icons/weather/drizzle.svg' },
  302: { desc: 'сильная морось', icon:  '/icons/weather/drizzle.svg' },
  310: { desc: 'слабый моросящий дождь', icon: '/icons/weather/extreme-drizzle.svg' },
  311: { desc: 'моросящий дождь', icon: '/icons/weather/extreme-drizzle.svg' },
  312: { desc: 'сильный моросящий дождь', icon:  '/icons/weather/extreme-drizzle.svg'},
  313: { desc: 'ливневый дождь и морось', icon: '/icons/weather/extreme-rain.svg'},
  314: { desc: 'ливневый дождь и изморось', icon: '/icons/weather/extreme-rain.svg'},
  321: { desc: 'ливень', icon: '/icons/weather/extreme-rain.svg'},
  500: { desc: 'небольшой дождь', icon: '/icons/weather/rain.svg'},
  501: { desc: 'умеренный дождь', icon: '/icons/weather/rain.svg'},
  502: { desc: 'сильный дождь', icon: '/icons/weather/rain.svg'},
  503: { desc: 'очень сильный дождь', icon: '/icons/weather/rain.svg'},
  504: { desc: 'сильный дождь', icon: '/icons/weather/rain.svg'},
  511: { desc: 'ледяной дождь', icon: '/icons/weather/rain.svg'},
  520: { desc: 'слабый ливневый дождь', icon: '/icons/weather/rain.svg'},
  521: { desc: 'ливень', icon: '/icons/weather/rain.svg'},
  522: { desc: 'сильный ливневый дождь', icon: '/icons/weather/rain.svg'},
  531: { desc: 'частично ливневый дождь', icon: '/icons/weather/rain.svg'},
  600: { desc: 'легкий снег', icon: '/icons/weather/snow.svg' },
  601: { desc: 'снег', icon: '/icons/weather/snow.svg' },
  602: { desc: 'сильный снегопад', icon: '/icons/weather/snow.svg' },
  611: { desc: 'мокрый снег', icon: '/icons/weather/sleet.svg'},
  612: { desc: 'слабый мокрый снег', icon: '/icons/weather/sleet.svg'},
  613: { desc: 'ливень с мокрым снегом', icon: '/icons/weather/extreme-sleet.svg'},
  615: { desc: 'небольшой дождь и снег', icon: '/icons/weather/sleet.svg'},
  616: { desc: 'дождь со снегом', icon: '/icons/weather/sleet.svg'},
  620: { desc: 'небольшой снегопад', icon: '/icons/weather/extreme-snow.svg'},
  621: { desc: 'снегопад', icon: '/icons/weather/extreme-snow.svg'},
  622: { desc: 'сильный снегопад', icon: '/icons/weather/extreme-snow.svg'},
  701: { desc: 'туман', icon: '/icons/weather/fog.svg'},
  711: { desc: 'дым', icon: '/icons/weather/smoke.svg'},
  721: { desc: 'дымка', icon: '/icons/weather/smoke.svg'},
  731: { desc: 'песчано-пыльные вихри', icon: '/icons/weather/dust-wind.svg'},
  741: { desc: 'смог', icon: '/icons/weather/mist.svg'},
  751: { desc: 'песок', icon: '/icons/weather/dust.svg'},
  761: { desc: 'пыль', icon: '/icons/weather/dust.svg'},
  762: { desc: 'вулканический пепел', icon: '/icons/weather/dust.svg'},
  771: { desc: 'шквал', icon: '/icons/weather/wind.svg'},
  781: { desc: 'смерч', icon: '/icons/weather/hurricane.svg'},
  800: { desc: 'безоблачно', icon: '/icons/weather/clear-day.svg' },
  801: { desc: 'небольшая облачность: 11-25%', icon: '/icons/weather/partly-cloudy-day.svg'},
  802: { desc: 'средняя облачность: 25-50%', icon: '/icons/weather/cloudy.svg'},
  803: { desc: 'высокая облачность: 51-84%', icon: '/icons/weather/overcast.svg'},
  804: { desc: 'очень высокая облачность: 85-100%', icon: '/icons/weather/extreme.svg'},
};