export const usersAdminList = [
  {
    'id': 4,
    'username': 'Agibalova_TV',
    'fullname': 'Агибалова Татьяна В',
    'dob': '11.11.1984',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Мильченко Евгения Александровна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 5,
    'username': 'Alekseeva_NY',
    'fullname': 'Алексеева Наталья Юрьевна',
    'dob': '03.06.1971',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Сабанцев Михаил Михайлович',
    'workplace': 'Кабинет 5, АРМ 2',
    'ip': '192.168.2.29',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 43,
    'username': 'Aseev_MS',
    'fullname': 'Асеев Максим Сергеевич',
    'dob': '01.05.1975',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 6,
    'username': 'Ashurova_DM',
    'fullname': 'Ашурова Дина Михайловна',
    'dob': '06.07.1989',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Павлова Ольга Олеговна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 54,
    'username': 'Barinov_VP',
    'fullname': 'Баринов Виктор Петрович',
    'dob': '20.10.1961',
    'profession': 'Заместитель председателя',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 44,
    'username': 'Basurova_EE',
    'fullname': 'Басурова Елена Евгеньевна',
    'dob': '30.01.1978',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 10, ARM 1',
    'ip': '192.168.2.68',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 7,
    'username': 'Berezovskaya_NV',
    'fullname': 'Березовская Наталья Васильевна',
    'dob': '24.05.1966',
    'profession': 'Специалист 1 разряда',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 1',
    'ip': '192.168.2.30',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 8,
    'username': 'Birukova_EV',
    'fullname': 'Бирюкова Елена Владимировна',
    'dob': '17.09.1983',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Тарасова Майя Александровна',
    'workplace': 'Кабинет 14, АРМ 3',
    'ip': '192.168.2.7',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 36,
    'username': 'Bogachev_SS',
    'fullname': 'Богачёв Сергей Станиславович',
    'dob': '12.11.1979',
    'profession': 'Администратор',
    'affiliationJudge': '',
    'workplace': 'Совещ. комн. зала № 5, АРМ 1',
    'ip': '192.168.2.71',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 55,
    'username': 'Burikin_NI',
    'fullname': 'Бурыкин Николай Иванович',
    'dob': '11.12.1955',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 59,
    'username': 'Bylinin_AV',
    'fullname': 'Былинин Александр Викторович',
    'dob': '19.02.1958',
    'profession': 'Старший специалист 1 разряда',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 53,
    'username': 'Vaiceshuk_IS',
    'fullname': 'Вайцещук Ирина Сергеевна',
    'dob': '04.03.1985',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 9,
    'username': 'Voropaeva_TV',
    'fullname': 'Воропаева Татьяна Викторовна',
    'dob': '16.11.1971',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': '',
    'workplace': 'Кабинет 14, АРМ 2',
    'ip': '192.168.2.28',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 10,
    'username': 'Gerasimova_NV',
    'fullname': 'Герасимова Наталья Владимировна',
    'dob': '24.09.1984',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Мельничук Елена Владимировна',
    'workplace': 'Кабинет 6, АРМ 2',
    'ip': '192.168.2.27',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 11,
    'username': 'Gorbacheva_AV',
    'fullname': 'Горбачева Анна Викторовна',
    'dob': '20.03.1990',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Соловьёв Вадим Геннадьевич',
    'workplace': 'Приёмная кабинет 1, АРМ 2',
    'ip': '192.168.2.21',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 56,
    'username': 'Gubareva_OV',
    'fullname': 'Губарева Ольга Валентиновна',
    'dob': '04.12.1983',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Вайцещук Ирина Сергеевна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 42,
    'username': 'Drozdov_SA',
    'fullname': 'Дроздов Сергей Алексеевич',
    'dob': '11.12.1970',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 8, АРМ 2',
    'ip': '192.168.2.66',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 61,
    'username': 'Ermoshenkova_OV',
    'fullname': 'Ермощенкова Ольга Васильевна',
    'dob': '01.11.1980',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Мильченко Евгения Александровна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 12,
    'username': 'Zueva_EV',
    'fullname': 'Зуева Елена Вячеславовна',
    'dob': '16.08.1985',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Басурова Елена Евгеньевна',
    'workplace': 'Кабинет 11, АРМ 1',
    'ip': '192.168.2.16',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 13,
    'username': 'Kaichenkova_EA',
    'fullname': 'Кайченкова Елена Анатольевна',
    'dob': '22.05.1983',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Дроздов Сергей Алексеевич',
    'workplace': 'Приёмная кабинет 8, АРМ 2',
    'ip': '192.168.2.14',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 14,
    'username': 'Kasyanova_SV',
    'fullname': 'Касьянова Светлана Викторовна',
    'dob': '22.05.1988',
    'profession': 'Рабочий, 2 разряд',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 8',
    'ip': '192.168.2.36',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 48,
    'username': 'Kovechenkova_YN',
    'fullname': 'Ковеченкова Юлия Николаевна',
    'dob': '16.06.1982',
    'profession': 'Помощник судьи',
    'affiliationJudge': '',
    'workplace': 'Кабинет 12, АРМ 2',
    'ip': '192.168.2.12',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 15,
    'username': 'Kovrigina_EN',
    'fullname': 'Ковригина Е Н',
    'dob': '01.04.2021',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Асеев Максим Сергеевич',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 37,
    'username': 'Kozlov_AA',
    'fullname': 'Козлов Андрей Альевич',
    'dob': '27.06.1970',
    'profession': 'Заместитель председателя',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 58,
    'username': 'Komyagina_LE',
    'fullname': 'Комягина Любовь Евгеньевна',
    'dob': '07.04.1970',
    'profession': 'Старший специалист 3 разряда',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 50,
    'username': 'Kostenkova_NA',
    'fullname': 'Костенкова Наталья Александровна',
    'dob': '17.06.1975',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Мильченко Евгения Александровна',
    'workplace': 'Кабинет 14, АРМ 1',
    'ip': '192.168.2.37',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 17,
    'username': 'Krivas_IV',
    'fullname': 'Кривас Ирина Владимировна',
    'dob': '25.10.1979',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Басурова Елена Евгеньевна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 41,
    'username': 'Krivchuk_VA',
    'fullname': 'Кривчук Вера Алексеевна',
    'dob': '22.12.1977',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 9, АРМ 1',
    'ip': '192.168.2.67',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 18,
    'username': 'Latysheva_YA',
    'fullname': 'Латышева Юлия Александровна',
    'dob': '11.09.1985',
    'profession': 'Консультант',
    'affiliationJudge': '',
    'workplace': 'Совещ. комн. зала № 4, АРМ 2',
    'ip': '192.168.2.2',
    'active': 1,
    'sudo': 1,
  },
  {
    'id': 16,
    'username': 'Lobanova_EV',
    'fullname': 'Лобанова Екатерина Владимировна',
    'dob': '09.03.1980',
    'profession': 'Секретарь суда',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 6',
    'ip': '192.168.2.34',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 19,
    'username': 'Maluchkova_EN',
    'fullname': 'Малючкова Евгения Николаевна',
    'dob': '17.08.1981',
    'profession': 'Начальник отдела',
    'affiliationJudge': '',
    'workplace': 'Кабинет 2, АРМ 2',
    'ip': '192.168.2.25',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 40,
    'username': 'Melnichuk_EV',
    'fullname': 'Мельничук Елена Владимировна',
    'dob': '02.09.1974',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 6, АРМ 1',
    'ip': '192.168.2.64',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 20,
    'username': 'Meshkova_VO',
    'fullname': 'Мешкова Виктория Олеговна',
    'dob': '19.10.1985',
    'profession': 'Старший специалист 3 разряда',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 4',
    'ip': '192.168.2.6',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 46,
    'username': 'Milchenko_EA',
    'fullname': 'Мильченко Евгения Александровна',
    'dob': '27.07.1982',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 13, АРМ 1',
    'ip': '192.168.2.4',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 21,
    'username': 'Mirenkova_YN',
    'fullname': 'Миренкова Юлия Николаевна',
    'dob': '14.11.1987',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Асеев Максим Сергеевич',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 65,
    'username': 'Molchanova_OP',
    'fullname': 'Молчанова Ольга Павловна',
    'dob': '26.12.1986',
    'profession': 'Старший специалист 3 разряда',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 52,
    'username': 'Morozova_YA',
    'fullname': 'Морозова Юлия Алексеевна',
    'dob': '26.05.1984',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Кривчук Вера Алексеевна',
    'workplace': 'Кабинет 9, АРМ 2',
    'ip': '192.168.2.17',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 22,
    'username': 'Nikolaeva_II',
    'fullname': 'Николаева Инга Игоревна',
    'dob': '21.07.1985',
    'profession': 'Старший специалист 2 разряда',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 3',
    'ip': '192.168.2.32',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 23,
    'username': 'Novichkova_AS',
    'fullname': 'Новичкова Анна Сергеевна',
    'dob': '24.04.1983',
    'profession': 'Помощник председателя суда',
    'affiliationJudge': 'Соловьёв Вадим Геннадьевич',
    'workplace': 'Приёмная кабинет 1, АРМ 1',
    'ip': '192.168.2.23',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 62,
    'username': 'Oreshkova_EO',
    'fullname': 'Орешкова Елена Олеговна',
    'dob': '20.09.1995',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Мельничук Елена Владимировна',
    'workplace': 'Кабинет 13, АРМ 2',
    'ip': '192.168.2.9',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 24,
    'username': 'Osipova_AV',
    'fullname': 'Осипова Анна Валерьевна',
    'dob': '27.11.1986',
    'profession': 'Консультант',
    'affiliationJudge': '',
    'workplace': 'Кабинет 2, АРМ 1',
    'ip': '192.168.2.26',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 49,
    'username': 'Pavlova_OO',
    'fullname': 'Павлова Ольга Олеговна',
    'dob': '03.12.1979',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 12, АРМ 1',
    'ip': '192.168.2.61',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 64,
    'username': 'Pankova_KV',
    'fullname': 'Панкова Ксения Васильевна',
    'dob': '17.08.1993',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Павлова Ольга Олеговна',
    'workplace': 'Кабинет 15, АРМ 1',
    'ip': '192.168.2.24',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 25,
    'username': 'Poluektova_SA',
    'fullname': 'Полуэктова Светлана Анатольевна',
    'dob': '28.03.1984',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Кривчук Вера Алексеевна',
    'workplace': 'Кабинет 15, АРМ 2',
    'ip': '192.168.2.19',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 26,
    'username': 'Prokofieva_MV',
    'fullname': 'Прокофьева Марина Викторовна',
    'dob': '07.10.1965',
    'profession': 'Ведущий специалист',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 2',
    'ip': '192.168.2.33',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 27,
    'username': 'Pshenichnikova_AV',
    'fullname': 'Пшеничникова Анастасия Вячеславовна',
    'dob': '24.11.1994',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Мельничук Елена Владимировна',
    'workplace': 'Кабинет 15, АРМ 3',
    'ip': '192.168.2.5',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 28,
    'username': 'Rakcheeva_OV',
    'fullname': 'Ракчеева Ольга Викторовна',
    'dob': '06.06.1980',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Штукина Светлана Евгеньевна',
    'workplace': 'Кабинет 16, АРМ 2',
    'ip': '192.168.2.10',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 39,
    'username': 'Sabantsev_MM',
    'fullname': 'Сабанцев Михаил Михайлович',
    'dob': '24.07.1955',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 5, АРМ 1',
    'ip': '192.168.2.63',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 29,
    'username': 'Salnikova_EG',
    'fullname': 'Сальникова Екатерина Геннадьевна',
    'dob': '11.07.1989',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Басурова Елена Евгеньевна',
    'workplace': 'Кабинет 11, АРМ 2',
    'ip': '192.168.2.11',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 47,
    'username': 'Sevrikova_VN',
    'fullname': 'Севрикова Валентина Николаевна',
    'dob': '25.07.1987',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Мильченко Евгения Александровна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 51,
    'username': 'Semenova_MN',
    'fullname': 'Семенова Марина Николаевна',
    'dob': '25.07.1976',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Дроздов Сергей Алексеевич',
    'workplace': 'Кабинет 8, АРМ 1',
    'ip': '192.168.2.13',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 3,
    'username': 'Soloviev_VG',
    'fullname': 'Соловьёв Вадим Геннадьевич',
    'dob': '24.01.1977',
    'profession': 'Председатель',
    'affiliationJudge': '',
    'workplace': 'Кабинет 1, АРМ 1',
    'ip': '192.168.2.22',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 57,
    'username': 'Stepanec_VS',
    'fullname': 'Степанец Виктория Сергеевна',
    'dob': '14.08.1986',
    'profession': 'Секретарь суда',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 7',
    'ip': '192.168.2.31',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 30,
    'username': 'Tarakanova_EV',
    'fullname': 'Тараканова Елизавета Васильевна',
    'dob': '16.07.1988',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Тарасова Майя Александровна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 38,
    'username': 'Tarasova_MA',
    'fullname': 'Тарасова Майя Александровна',
    'dob': '05.05.1973',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 4, АРМ 1',
    'ip': '192.168.2.115',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 60,
    'username': 'Tverdyakova_NS',
    'fullname': 'Твердякова Наталья Сергеевна',
    'dob': '25.12.1972',
    'profession': 'Старший специалист 1 разряда',
    'affiliationJudge': '',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 31,
    'username': 'Timofeeva_II',
    'fullname': 'Тимофеева Ирина Ивановна',
    'dob': '03.02.1982',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Штукина Светлана Евгеньевна',
    'workplace': 'Кабинет 11, АРМ 3',
    'ip': '192.168.2.38',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 32,
    'username': 'Umerenkova_EV',
    'fullname': 'Умеренкова Елена Владимировна',
    'dob': '30.08.1983',
    'profession': 'Заместитель начальника отдела',
    'affiliationJudge': '',
    'workplace': 'Кабинет 3, АРМ 5',
    'ip': '192.168.2.35',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 33,
    'username': 'Franc_SK',
    'fullname': 'Франц Светлана Константиновна',
    'dob': '11.09.1996',
    'profession': 'Помощник судьи',
    'affiliationJudge': 'Мильченко Евгения Александровна',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 63,
    'username': 'Frolenkova_GV',
    'fullname': 'Фроленкова Глафира Владимировна',
    'dob': '14.12.1985',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': '',
    'workplace': 'Приёмная кабинет 7, АРМ 2',
    'ip': '192.168.2.20',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 34,
    'username': 'Homenkova_YA',
    'fullname': 'Хоменкова Юлия Анатольевна',
    'dob': '30.09.1978',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Сабанцев Михаил Михайлович',
    'workplace': 'Приёмная кабинет 8, АРМ 1',
    'ip': '192.168.2.15',
    'active': 1,
    'sudo': 0,
  },
  {
    'id': 35,
    'username': 'Cherkashina_SA',
    'fullname': 'Черкашина Светлана Анатольевна',
    'dob': '21.07.1968',
    'profession': 'Секретарь судебного заседания',
    'affiliationJudge': 'Сабанцев Михаил Михайлович',
    'workplace': 'нет кабинета, нет рабочего места',
    'ip': '',
    'active': 0,
    'sudo': 0,
  },
  {
    'id': 2,
    'username': 'Chernov_RA',
    'fullname': 'Чернов Роман Александрович',
    'dob': '17.03.1987',
    'profession': 'Консультант',
    'affiliationJudge': '',
    'workplace': 'Совещ. комн. зала № 4, АРМ 1',
    'ip': '192.168.2.3',
    'active': 1,
    'sudo': 1,
  },
  {
    'id': 45,
    'username': 'Shtukina_SE',
    'fullname': 'Штукина Светлана Евгеньевна',
    'dob': '04.11.1972',
    'profession': 'Судья',
    'affiliationJudge': '',
    'workplace': 'Кабинет 16, АРМ 1',
    'ip': '192.168.2.65',
    'active': 1,
    'sudo': 0,
  },
];
