create table sdc_calendar
(
    id          int(10) auto_increment comment 'Event ID',
    title       varchar(100) collate utf8mb4_unicode_ci            not null comment 'Event Title',
    description text collate utf8mb4_unicode_ci                    not null comment 'Event Description',
    start       datetime                                           null comment 'Event Date Time start',
    end         datetime                                           null comment 'Event Date Time End',
    allDay      varchar(1) collate utf8mb4_unicode_ci   default '' not null comment 'All day Event',
    calendar    varchar(100) collate utf8mb4_unicode_ci default '' not null comment 'Event''s Background Color',
    url         varchar(100) collate utf8mb4_unicode_ci default '' not null comment 'Event''s URL',
    user_id     int(10)                                            not null comment 'Event''s Ovner ID',
    freq        varchar(50)                                        null comment 'Event Repeat Freq String',
    tzid        varchar(100)                                       null comment 'Event''s Timezone',
    count       int                                                null comment 'Event''s Repeats Count',
    `interval`  int                                                null comment 'Event''s Repeating Interval',
    dtstart     datetime                                           null comment 'Event''s Repeating Date Time Start',
    until       datetime                                           null comment 'Event''s Repeating Date Time End',
    bymonth     varchar(50)                                        null comment 'Event''s Repeating by month array string',
    byweekday   varchar(50)                                        null comment 'Event''s Repeating by week day array string',
    constraint id
        unique (id)
)
    comment 'Events Fullcalendar Module';

alter table sdc_calendar
    add primary key (id);

INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (1, 'Закрытие суда', 'Чернов Роман Александрович', '2021-08-01 00:00:00', '2021-08-01 00:00:00', '1', 'Primary', '', 1, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (2, 'Консультант +', 'Отправить статистику Консультант+', '2021-08-20 00:00:00', '2021-08-20 00:00:00', '1', 'Info', 'sobyitiya/konsultant', 1, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (3, 'Справка к совещанию председателей', 'Подготовить справку отправить на Смоленский областной суд; ''gk_smoloblsud@mail.ru''; ''uk_smoloblsud@mail.ru''; ''adm_smoloblsud@mail.ru''; ''ok_smoloblsud@mail.ru''; ''smoloblsud@mail.ru ''', '2021-08-16 00:00:00', '2021-08-16 00:00:00', '0', 'Warning', '', 1, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (4, 'Статистическая отчетность', 'До 10 июля', '2021-08-09 00:00:00', '2021-08-09 00:00:00', '0', 'Primary', 'sobyitiya/polugodovaya-otchetnost', 1, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (5, 'Справка', 'Отправить подготовленные спраки', '2021-08-21 00:00:00', '2021-08-21 00:00:00', '0', 'Warning', 'sobyitiya/spravka-k-soveshhaniyu-predsedatelej', 1, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (6, 'Видеоконференц-связь', 'Проведение тестового сеанса ВКС перед совещанием председателей в 14:00', '2021-08-09 00:00:00', '2021-08-09 00:00:00', '0', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (7, 'Видеоконференц-связь', 'Проведение тестового сеанса ВКС перед совещанием председателей в 14:00', '2021-08-16 00:00:00', '2021-08-16 00:00:00', '0', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (8, 'Видеоконференц-связь', 'Проведение тестового сеанса ВКС перед совещанием по СМИ в 14:00', '2021-08-27 00:00:00', '2021-08-27 00:00:00', '0', 'Success', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (9, 'Тестовая запись на несколько дней', '', '2021-08-03 12:00:00', '2021-08-11 12:00:00', '', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (10, 'Тестовая запись', '', '2021-05-06 12:00:00', '2021-05-06 12:00:00', '', 'Success', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (11, 'Тестовое событие', '', '2021-08-05 12:00:00', '2021-08-05 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (12, 'Тестовая запись', '', '2021-07-22 12:00:00', '2021-07-22 12:00:00', '', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (13, 'Тестовая запись', '', '2021-08-19 12:00:00', '2021-08-19 12:00:00', '', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (14, 'Тестовая запись', '', '2021-05-12 12:00:00', '2021-05-12 12:00:00', '', 'Info', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (15, 'Тестовая запись', '', '2021-05-13 12:00:00', '2021-05-13 12:00:00', '', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (16, 'Тестовая запись', '', '2021-05-05 12:00:00', '2021-05-05 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (17, 'Тестовая запись', '', '2021-05-04 12:00:00', '2021-05-04 12:00:00', '', 'Info', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (18, 'Тестовая запись', '', '2021-05-03 12:00:00', '2021-05-03 12:00:00', '', 'Success', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (19, 'Тестовая запись', '', '2021-05-07 12:00:00', '2021-05-07 12:00:00', '', 'Success', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (20, 'Запись пользователя 2', '', '2021-05-08 12:00:00', '2021-05-08 12:00:00', '', 'Primary', '', 2, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (21, 'Тестовая Запись пользователя 3', '', '2021-05-10 12:00:00', '2021-05-10 12:00:00', '', 'Primary', '', 3, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (22, 'Запись пользователя 4', '', '2021-05-11 12:00:00', '2021-05-11 12:00:00', '', 'Warning', '', 4, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (23, 'Запись пользователя 5', '', '2021-05-14 12:00:00', '2021-05-14 12:00:00', '', 'Warning', '', 5, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (24, 'Тестовая запись', '', '2021-05-15 12:00:00', '2021-05-15 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (25, 'Тестовая запись', '', '2021-05-17 12:00:00', '2021-05-17 12:00:00', '', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (26, 'Тестовая запись', '', '2021-06-18 12:00:00', '2021-06-18 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (27, 'Тестовая запись', '', '2021-05-19 12:00:00', '2021-05-19 12:00:00', '', 'Info', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (28, 'Тестовая запись', '', '2021-05-20 12:00:00', '2021-05-20 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (29, 'Тестовая запись', '', '2021-05-21 12:00:00', '2021-05-21 12:00:00', '', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (30, 'Тестовая запись', '', '2021-05-24 12:00:00', '2021-05-24 12:00:00', '', 'Info', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (31, 'Тестовая запись', '', '2021-05-25 12:00:00', '2021-05-25 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (33, 'Тестовая запись', '', '2021-08-25 12:00:00', '2021-08-25 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (34, 'Тестовое событие', 'Описание', '2021-08-13 12:00:00', '2021-08-13 12:00:00', '1', 'Info', '', 1, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (49, '1', '', '2021-08-18 12:00:00', '2021-08-18 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (50, '1', '', '2021-08-26 12:00:00', '2021-08-26 12:00:00', '', 'Info', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (53, '42323', '', '2021-08-25 12:00:00', '2021-08-25 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (57, '3', '', '2021-08-23 12:00:00', '2021-08-23 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (59, '5', '', '2021-08-31 12:00:00', '2021-08-31 12:00:00', '', 'Primary', 'http://google.com', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (63, '1', '', '2021-08-17 12:00:00', '2021-08-17 12:00:00', '', 'Warning', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (68, '1', '', '2021-08-15 12:00:00', '2021-08-15 12:00:00', '', 'Primary', '', 0, null, 'Europe/Moscow', null, null, null, null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (83, 'Повторяющееся каждый день 3 раза', '', '2021-08-06 12:00:00', '2021-08-06 12:00:00', '', 'Primary', '', 0, 'DAILY', 'Europe/Moscow', 3, 1, '2021-08-06 12:00:00', null, null, null);
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, tzid, count, `interval`, dtstart, until, bymonth, byweekday) VALUES (84, 'Повторяется каждую неделю в пн до 31.08.2021', 'и хотя дата события 1 августа, событие 2 августа', '2021-08-01 12:00:00', '2021-08-01 12:00:00', '', 'Primary', '', 0, 'WEEKLY', 'Europe/Moscow', null, 1, '2021-08-01 12:00:00', '2021-08-31 12:00:00', null, 'MO');