create table sdc_calendar
(
    id          int(10) auto_increment,
    title       varchar(100) collate utf8mb4_unicode_ci default ''     null,
    description text collate utf8mb4_unicode_ci         default ''     null,
    start       datetime                                               not null,
    end         datetime                                               not null,
    allDay      varchar(1) collate utf8mb4_unicode_ci   default ''     null,
    calendar    varchar(100) collate utf8mb4_unicode_ci default ''     not null,
    url         varchar(100) collate utf8mb4_unicode_ci default ''     null,
    user_id     int(10)                                                not null,
    freq        varchar(50)                                            null,
    dtstart     datetime                                               null,
    tzid        varchar(100)                                           null,
    until       datetime                                               null,
    count       int                                                    null,
    `interval`  int                                                    null,
    byweekday   varchar(50)                                            null,
    bymonth     varchar(50)                                            null,
    bysetpos    int                                                    null,
    bymonthday  varchar(150)                                           null,
    byyearday   varchar(2000)                                          null,
    byweekno    varchar(250)                                           null,
    display     varchar(50)                             default 'auto' not null,
    constraint sdc_calendar_id_uindex
        unique (id)
);

alter table sdc_calendar
    add primary key (id);

INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (1, 'Запись №1. Не повторяется', 'Описание', '2021-08-22 15:26:01', '2021-08-22 15:26:03', '', 'Primary', 'https://jakubroztocil.github.io/rrule/', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'auto');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (2, 'Посторяющееся ежедневно событие через 3 дня', 'Большое описание события, не имеющее смысла', '2021-08-22 15:44:47', '2021-08-22 15:44:54', '1', 'Warning', 'https://momentjs.com/docs/#/manipulating/local/', 1, 'DAILY', '2021-08-22 15:44:47', 'Europe/Moscow', null, 4, 3, null, null, null, null, null, null, 'auto');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (3, 'Еженедельно по поднедельникам 5 раз, без интервала', '', '2021-08-02 00:00:00', '2021-08-02 00:00:00', '1', 'Info', 'https://jakubroztocil.github.io/rrule/', 0, 'WEEKLY', '2021-08-01 15:50:23', 'Europe/Moscow', null, 5, 1, 'MO', null, null, null, null, null, 'auto');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (4, 'Еженедельно по вторникам 2 раза, интервал 2', '', '2021-08-01 15:50:23', '2021-08-01 15:50:23', '1', 'Success', 'https://jakubroztocil.github.io/rrule/', 0, 'WEEKLY', '2021-08-01 15:50:23', 'Europe/Moscow', null, 2, 2, 'TU', null, null, null, null, null, 'auto');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (5, 'Ежемесячно до конца года', '', '2021-08-01 15:50:23', '2021-08-01 15:50:23', '1', 'Warning', 'https://jakubroztocil.github.io/rrule/', 0, 'MONTHLY', '2021-08-01 15:50:23', 'Europe/Moscow', '2021-12-31 15:50:23', null, 2, null, null, null, null, null, null, 'auto');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (6, '', '', '2021-07-31 00:00:00', '2021-07-31 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (7, '', '', '2021-08-01 00:00:00', '2021-08-01 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (8, '', '', '2021-08-07 00:00:00', '2021-08-07 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (9, '', '', '2021-08-08 00:00:00', '2021-08-08 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (10, '', '', '2021-08-14 00:00:00', '2021-08-14 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (11, '', '', '2021-08-15 00:00:00', '2021-08-15 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (12, '', '', '2021-08-21 00:00:00', '2021-08-21 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (13, '', '', '2021-08-22 00:00:00', '2021-08-22 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (14, '', '', '2021-08-28 00:00:00', '2021-08-28 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (15, '', '', '2021-08-29 00:00:00', '2021-08-29 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (16, '', '', '2021-09-04 00:00:00', '2021-09-04 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (17, '', '', '2021-09-05 00:00:00', '2021-09-05 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (18, '', '', '2021-09-11 00:00:00', '2021-09-11 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (19, '', '', '2021-09-12 00:00:00', '2021-09-12 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (20, '', '', '2021-09-18 00:00:00', '2021-09-18 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (21, '', '', '2021-09-19 00:00:00', '2021-09-19 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (22, '', '', '2021-09-25 00:00:00', '2021-09-25 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (23, '', '', '2021-09-26 00:00:00', '2021-09-26 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (24, '', '', '2021-10-02 00:00:00', '2021-10-02 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (25, '', '', '2021-10-03 00:00:00', '2021-10-03 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (26, '', '', '2021-10-09 00:00:00', '2021-10-09 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (27, '', '', '2021-10-10 00:00:00', '2021-10-10 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (28, '', '', '2021-10-16 00:00:00', '2021-10-16 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (29, '', '', '2021-10-17 00:00:00', '2021-10-17 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (30, '', '', '2021-10-23 00:00:00', '2021-10-23 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (31, '', '', '2021-10-24 00:00:00', '2021-10-24 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (32, '', '', '2021-10-30 00:00:00', '2021-10-30 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (33, '', '', '2021-10-31 00:00:00', '2021-10-31 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (34, 'Сокращенный рабочий день', '', '2021-11-03 00:00:00', '2021-11-03 23:59:59', '1', 'Warning', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (35, '', '', '2021-11-04 00:00:00', '2021-11-04 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (36, '', '', '2021-11-05 00:00:00', '2021-11-05 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (37, '', '', '2021-11-06 00:00:00', '2021-11-06 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (38, '', '', '2021-11-07 00:00:00', '2021-11-07 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (39, '', '', '2021-11-13 00:00:00', '2021-11-13 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (40, '', '', '2021-11-14 00:00:00', '2021-11-14 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (41, '', '', '2021-11-20 00:00:00', '2021-11-20 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (42, '', '', '2021-11-21 00:00:00', '2021-11-21 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (43, '', '', '2021-11-27 00:00:00', '2021-11-27 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');
INSERT INTO isp.sdc_calendar (id, title, description, start, end, allDay, calendar, url, user_id, freq, dtstart, tzid, until, count, `interval`, byweekday, bymonth, bysetpos, bymonthday, byyearday, byweekno, display) VALUES (44, '', '', '2021-11-28 00:00:00', '2021-11-28 23:59:59', '1', 'Danger', '', 0, null, null, 'Europe/Moscow', null, null, null, null, null, null, null, null, null, 'background');